  runtime: python27
  api_version: 1
  threadsafe: true

  libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest

  handlers:

  - url: /img/(.+)
    static_files: img/\1
    upload: img/(.*)     

  - url: /.*
    script: app.app


  skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
  - /public/landing/bower_components$
  - /public/landing/node_modules$